import type { Lead } from "@/types/lead";
import type { Task } from "@/types/task";
import type {
  Workflow,
  WorkflowStatus,
  WorkflowStep,
} from "@/types/workflow";

export type ActivityType =
  | "workflow"
  | "lead"
  | "task"
  | "ai";

export interface Activity {
  id: string;
  type: ActivityType;
  title: string;
  description: string;
  createdAt: string;
}

const now = new Date().toISOString();

const starterWorkflowSteps: WorkflowStep[] = [
  {
    id: "step-trigger-1",
    title: "Incoming Request",
    description: "Receive and analyze a new customer request.",
    type: "trigger",
    order: 1,
    config: {},
  },
  {
    id: "step-ai-1",
    title: "AI Analysis",
    description: "AI classifies the request and determines intent.",
    type: "ai",
    order: 2,
    config: {},
  },
  {
    id: "step-action-1",
    title: "Take Action",
    description: "Execute the appropriate automation action.",
    type: "action",
    order: 3,
    config: {},
  },
];

const workflows: Workflow[] = [
  {
    id: "workflow-1",
    name: "Customer Support Automation",
    description:
      "Automatically classify and respond to customer inquiries.",
    status: "active",
    runs: 248,
    successRate: 96,
    steps: starterWorkflowSteps,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "workflow-2",
    name: "Lead Qualification",
    description:
      "Analyze incoming leads and assign priority automatically.",
    status: "active",
    runs: 182,
    successRate: 94,
    steps: [
      {
        id: "step-trigger-2",
        title: "New Lead",
        description: "Detect a newly created lead.",
        type: "trigger",
        order: 1,
        config: {},
      },
      {
        id: "step-ai-2",
        title: "AI Qualification",
        description: "Evaluate lead quality and buying intent.",
        type: "ai",
        order: 2,
        config: {},
      },
      {
        id: "step-action-2",
        title: "Assign Priority",
        description: "Assign a priority based on AI analysis.",
        type: "action",
        order: 3,
        config: {},
      },
    ],
    createdAt: now,
    updatedAt: now,
  },
];

const leads: Lead[] = [
  {
    id: "lead-1",
    name: "Sarah Khan",
    email: "sarah@example.com",
    company: "Khan Fashion",
    phone: "+92 300 1234567",
    status: "qualified",
    priority: "high",
    notes: "Interested in automation services.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lead-2",
    name: "Ali Raza",
    email: "ali@example.com",
    company: "Raza Digital",
    phone: "+92 301 7654321",
    status: "contacted",
    priority: "medium",
    notes: "Follow up next week.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "lead-3",
    name: "Emma Wilson",
    email: "emma@example.com",
    company: "Wilson Studio",
    status: "new",
    priority: "low",
    notes: "New inbound lead.",
    createdAt: now,
    updatedAt: now,
  },
];

const tasks: Task[] = [
  {
    id: "task-1",
    title: "Follow up with qualified leads",
    description:
      "Contact qualified leads generated by the support workflow.",
    status: "in_progress",
    priority: "high",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-2",
    title: "Review AI responses",
    description:
      "Review recent AI-generated customer responses.",
    status: "pending",
    priority: "medium",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "task-3",
    title: "Optimize workflow",
    description:
      "Review workflow performance and improve automation steps.",
    status: "completed",
    priority: "low",
    createdAt: now,
    updatedAt: now,
  },
];

const activities: Activity[] = [
  {
    id: "activity-1",
    type: "workflow",
    title: "Customer Support Automation completed",
    description: "AI processed recent customer inquiries.",
    createdAt: now,
  },
  {
    id: "activity-2",
    type: "lead",
    title: "New lead added",
    description: "Emma Wilson was added to leads.",
    createdAt: now,
  },
  {
    id: "activity-3",
    type: "task",
    title: "Follow-up task created",
    description: "Follow up with qualified leads.",
    createdAt: now,
  },
];

/* -------------------------------------------------------------------------- */
/* WORKFLOWS                                                                   */
/* -------------------------------------------------------------------------- */

export function getWorkflows(): Workflow[] {
  return workflows;
}

export function getWorkflowById(id: string): Workflow | undefined {
  return workflows.find((workflow) => workflow.id === id);
}

export function createWorkflow(workflow: Workflow): Workflow {
  workflows.unshift(workflow);

  addActivity({
    type: "workflow",
    title: "New workflow created",
    description: `${workflow.name} was created.`,
  });

  return workflow;
}

export function updateWorkflow(
  id: string,
  data: Partial<Workflow>
): Workflow | undefined {
  const workflow = getWorkflowById(id);

  if (!workflow) {
    return undefined;
  }

  Object.assign(workflow, {
    ...data,
    id: workflow.id,
    updatedAt: new Date().toISOString(),
  });

  return workflow;
}

export function deleteWorkflow(id: string): boolean {
  const index = workflows.findIndex(
    (workflow) => workflow.id === id
  );

  if (index === -1) {
    return false;
  }

  workflows.splice(index, 1);

  return true;
}

export function updateWorkflowStatus(
  id: string,
  status: WorkflowStatus
): Workflow | undefined {
  return updateWorkflow(id, { status });
}
export function runWorkflow(id: string) {
  const workflow = getWorkflowById(id);

  if (!workflow) {
    return undefined;
  }

  const success = Math.random() < 0.95;

  workflow.runs += 1;

  const previousRuns = workflow.runs - 1;

  workflow.successRate =
    previousRuns === 0
      ? success
        ? 100
        : 0
      : Number(
          (
            ((workflow.successRate * previousRuns +
              (success ? 100 : 0)) /
              workflow.runs)
          ).toFixed(1)
        );

  workflow.updatedAt = new Date().toISOString();

  addActivity({
    type: "workflow",
    title: `${workflow.name} executed`,
    description: success
      ? "Workflow completed successfully."
      : "Workflow execution requires review.",
  });

  return {
    workflow,
    run: {
      id: `run-${Date.now()}`,
      workflowId: workflow.id,
      status: success ? "success" : "failed",
      createdAt: new Date().toISOString(),
    },
  };
}
/* -------------------------------------------------------------------------- */
/* LEADS                                                                       */
/* -------------------------------------------------------------------------- */

export function getLeads(): Lead[] {
  return leads;
}

export function getLeadById(id: string): Lead | undefined {
  return leads.find((lead) => lead.id === id);
}

export function createLead(lead: Lead): Lead {
  leads.unshift(lead);

  addActivity({
    type: "lead",
    title: "New lead added",
    description: `${lead.name} was added to leads.`,
  });

  return lead;
}

export function updateLead(
  id: string,
  data: Partial<Lead>
): Lead | undefined {
  const lead = getLeadById(id);

  if (!lead) {
    return undefined;
  }

  Object.assign(lead, {
    ...data,
    id: lead.id,
    updatedAt: new Date().toISOString(),
  });

  return lead;
}

export function deleteLead(id: string): boolean {
  const index = leads.findIndex((lead) => lead.id === id);

  if (index === -1) {
    return false;
  }

  leads.splice(index, 1);

  return true;
}

/* -------------------------------------------------------------------------- */
/* TASKS                                                                       */
/* -------------------------------------------------------------------------- */

export function getTasks(): Task[] {
  return tasks;
}

export function getTaskById(id: string): Task | undefined {
  return tasks.find((task) => task.id === id);
}

export function createTask(task: Task): Task {
  tasks.unshift(task);

  addActivity({
    type: "task",
    title: "New task created",
    description: `${task.title} was added to tasks.`,
  });

  return task;
}

export function updateTask(
  id: string,
  data: Partial<Task>
): Task | undefined {
  const task = getTaskById(id);

  if (!task) {
    return undefined;
  }

  Object.assign(task, {
    ...data,
    id: task.id,
    updatedAt: new Date().toISOString(),
  });

  return task;
}

export function deleteTask(id: string): boolean {
  const index = tasks.findIndex((task) => task.id === id);

  if (index === -1) {
    return false;
  }

  tasks.splice(index, 1);

  return true;
}

/* -------------------------------------------------------------------------- */
/* ACTIVITY                                                                    */
/* -------------------------------------------------------------------------- */

export function getRecentActivity(limit = 10): Activity[] {
  return [...activities]
    .sort(
      (a, b) =>
        new Date(b.createdAt).getTime() -
        new Date(a.createdAt).getTime()
    )
    .slice(0, limit);
}

export function addActivity(
  activity: Omit<Activity, "id" | "createdAt">
): Activity {
  const newActivity: Activity = {
    id: `activity-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 8)}`,
    createdAt: new Date().toISOString(),
    ...activity,
  };

  activities.unshift(newActivity);

  return newActivity;
}

/* -------------------------------------------------------------------------- */
/* DASHBOARD / ANALYTICS                                                       */
/* -------------------------------------------------------------------------- */

export function getDashboardStats() {
  const totalRuns = workflows.reduce(
    (total, workflow) => total + workflow.runs,
    0
  );

  const activeWorkflows = workflows.filter(
    (workflow) => workflow.status === "active"
  ).length;

  const successRate =
    totalRuns === 0
      ? 0
      : workflows.reduce(
          (total, workflow) =>
            total + workflow.runs * workflow.successRate,
          0
        ) / totalRuns;

  return {
    workflows: workflows.length,
    activeWorkflows,
    leads: leads.length,
    tasks: tasks.length,
    aiRuns: totalRuns,
    successRate: Number(successRate.toFixed(1)),
  };
}

export function getAnalytics() {
  const totalRuns = workflows.reduce(
    (total, workflow) => total + workflow.runs,
    0
  );

  const successfulRuns = workflows.reduce(
    (total, workflow) =>
      total +
      Math.round(
        workflow.runs * (workflow.successRate / 100)
      ),
    0
  );

  const failedRuns = Math.max(
    totalRuns - successfulRuns,
    0
  );

  const successRate =
    totalRuns === 0
      ? 0
      : Number(
          ((successfulRuns / totalRuns) * 100).toFixed(1)
        );

  return {
    totalRuns,
    successfulRuns,
    failedRuns,
    successRate,
    leadsGenerated: leads.length,
    tasksCreated: tasks.length,
    workflows: workflows.length,
    activeWorkflows: workflows.filter(
      (workflow) => workflow.status === "active"
    ).length,
  };
}

/* -------------------------------------------------------------------------- */
/* SHARED STORE SNAPSHOT                                                       */
/* -------------------------------------------------------------------------- */

export function getStoreSnapshot() {
  const dashboard = getDashboardStats();
  const analytics = getAnalytics();

  return {
    workflows: getWorkflows(),
    leads: getLeads(),
    tasks: getTasks(),
    activities: getRecentActivity(),
    dashboard,
    analytics,
  };
}
/* -------------------------------------------------------------------------- */
/* LEGACY STORE COMPATIBILITY                                                  */
/* -------------------------------------------------------------------------- */

export const workflowStore = {
  get workflows() {
    return workflows;
  },
};

export const leadStore = {
  get leads() {
    return leads;
  },
};

export const taskStore = {
  get tasks() {
    return tasks;
  },
};
