
import { NextResponse } from "next/server";
import { createTaskSchema } from "@/lib/validations/task";
import type { Task } from "@/types/task";

const tasks: Task[] = [
  {
    id: "task-1",
    title: "Follow up with qualified leads",
    description: "Contact qualified leads generated by the support workflow.",
    status: "in_progress",
    priority: "high",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-2",
    title: "Review AI responses",
    description: "Review recent AI-generated customer responses.",
    status: "pending",
    priority: "medium",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "task-3",
    title: "Optimize workflow",
    description: "Review workflow performance and improve automation steps.",
    status: "completed",
    priority: "low",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export async function GET() {
  return NextResponse.json({
    success: true,
    tasks,
  });
}

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const validation = createTaskSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: "Invalid task data.",
          details: validation.error.flatten(),
        },
        { status: 400 }
      );
    }

    const now = new Date().toISOString();

    const task: Task = {
      id: `task-${Date.now()}`,
      ...validation.data,
      description: validation.data.description ?? "",
      status: validation.data.status ?? "pending",
      priority: validation.data.priority ?? "medium",
      createdAt: now,
      updatedAt: now,
    };

    tasks.unshift(task);

    return NextResponse.json(
      {
        success: true,
        task,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Create task error:", error);

    return NextResponse.json(
      {
        success: false,
        error: "Unable to create task.",
      },
      { status: 500 }
    );
  }
}
