"use client";

import { useEffect, useState } from "react";
import Card from "@/components/ui/Card";

interface Lead {
id: string;
name: string;
email: string;
company?: string;
status: string;
priority: string;
}

export default function LeadsPage() {
const [leads, setLeads] = useState<Lead[]>([]);
const [loading, setLoading] = useState(true);

useEffect(() => {
fetch("/api/leads")
.then((res) => res.json())
.then((data) => setLeads(data.leads || []))
.catch(() => setLeads([]))
.finally(() => setLoading(false));
}, []);

return ( <div className="space-y-8"> <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"> <div> <p className="text-sm font-medium text-violet-400">CRM</p> <h1 className="mt-1 text-3xl font-bold text-white">Leads</h1> <p className="mt-2 text-sm text-slate-400">
Track, qualify and manage leads generated by your automations. </p> </div>

```
    <button
      type="button"
      className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white hover:bg-violet-500"
    >
      + Add lead
    </button>
  </div>

  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
    {[
      ["Total leads", leads.length, "👥"],
      [
        "New",
        leads.filter((lead) => lead.status === "new").length,
        "✨",
      ],
      [
        "Qualified",
        leads.filter((lead) => lead.status === "qualified").length,
        "✓",
      ],
      [
        "High priority",
        leads.filter((lead) => lead.priority === "high").length,
        "🔥",
      ],
    ].map(([label, value, icon]) => (
      <Card key={String(label)}>
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-400">{label}</p>
            <p className="mt-2 text-2xl font-bold text-white">{value}</p>
          </div>
          <span className="text-xl">{icon}</span>
        </div>
      </Card>
    ))}
  </div>

  <Card className="overflow-hidden p-0">
    <div className="border-b border-white/10 px-5 py-5">
      <h2 className="font-semibold text-white">Lead pipeline</h2>
    </div>

    {loading ? (
      <div className="space-y-3 p-5">
        {[1, 2, 3].map((item) => (
          <div
            key={item}
            className="h-16 animate-pulse rounded-xl bg-white/5"
          />
        ))}
      </div>
    ) : (
      <div className="overflow-x-auto">
        <table className="w-full min-w-[650px]">
          <thead>
            <tr className="border-b border-white/10 text-left text-xs uppercase tracking-wider text-slate-500">
              <th className="px-5 py-4">Lead</th>
              <th className="px-5 py-4">Company</th>
              <th className="px-5 py-4">Status</th>
              <th className="px-5 py-4">Priority</th>
            </tr>
          </thead>

          <tbody>
            {leads.map((lead) => (
              <tr
                key={lead.id}
                className="border-b border-white/5 transition hover:bg-white/[0.03]"
              >
                <td className="px-5 py-4">
                  <div className="flex items-center gap-3">
                    <div className="flex h-9 w-9 items-center justify-center rounded-full bg-violet-500/10 text-xs font-semibold text-violet-300">
                      {lead.name
                        .split(" ")
                        .map((word) => word[0])
                        .join("")
                        .slice(0, 2)
                        .toUpperCase()}
                    </div>

                    <div>
                      <p className="text-sm font-medium text-white">
                        {lead.name}
                      </p>
                      <p className="text-xs text-slate-500">
                        {lead.email}
                      </p>
                    </div>
                  </div>
                </td>

                <td className="px-5 py-4 text-sm text-slate-400">
                  {lead.company || "—"}
                </td>

                <td className="px-5 py-4">
                  <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs capitalize text-emerald-400">
                    {lead.status}
                  </span>
                </td>

                <td className="px-5 py-4">
                  <span className="rounded-full bg-white/5 px-2.5 py-1 text-xs capitalize text-slate-300">
                    {lead.priority}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )}

    {!loading && leads.length === 0 && (
      <div className="p-12 text-center text-sm text-slate-500">
        No leads found.
      </div>
    )}
  </Card>
</div>

);
}
